### ISSUE TITLE
HW #5 Complete

### ISSUE THREAD

**Issue by HannahCBrunelle** [HannahCBrunelle/Brunelle_SpatialEcology#7]

**Comment by fitzLab-AL** [comment]
hi @HannahCBrunelle I graded the file named: Brunelle_HW5.R. It was incomplete, so let me know if I didn't grade the correct file / version. 

A few comments on this assignment:

1. When I ran your code, I ended up with a table that had duplicated columns for the bioclimatic variables. I thought we fixed this when we met over zoom, but it seems the problem remained. 
2. Lines 220-228 would not work for me, but it didn't really impact anything as we didn't need to use checkerboard partitioning for this assignment.
3. Some of your code wouldn't run because the libraries were not loaded (dismo, raster).
4. Your mahal model was not correct because your stack contained only bio2. The error is on line 285 where you convert the stack to a raster object. Again, I thought we solved this during our zoom meeting.
5. You didn't fit the maxent model or answer any of the questions.

GRADE: 3/10

**Comment by fitzLab-AL** [comment]
@HannahCBrunelle I graded the updated version of your HW code. Please check my solution for how to perform model evaluation (the test data are used to evaluate the model, not to fit and predict a new model) and to compare my answers to the HW questions to yours. 

GRADE: 7/10
